package env

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type Env map[string]string

// String converts environment variables map to newline-separated key=value pairs for GitHub Actions
func (e Env) String() string {
	var env []string

	for name, value := range e {
		env = append(env, fmt.Sprintf("%s=%s", name, value))
	}

	sort.Strings(env)
	return strings.Join(env, "\n")
}

// Setenv writes environment variables to GITHUB_ENV for GitHub Actions consumption
func Setenv(envm Env) error {
	env, err := os.OpenFile(os.Getenv("GITHUB_ENV"), os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
	// should never happen,
	// it means current runtime is not Github actions if there's any errors
	if err != nil {
		return err
	}

	_, err = env.WriteString(envm.String())
	if err != nil {
		return err
	}

	// make sure we write it to the GITHUB_ENV
	return env.Close()
}

// SetOutput writes workflow outputs to GITHUB_OUTPUT for GitHub Actions
func SetOutput(envm Env) error {
	env, err := os.OpenFile(os.Getenv("GITHUB_OUTPUT"), os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
	if err != nil {
		return err
	}

	_, err = env.WriteString(envm.String())
	if err != nil {
		return err
	}

	return env.Close()
}

// Changes returns the changed files in current PR,
// which depends on ALL_CHANGED_FILES generated by tj-actions/changed-files action,
// if there's no content in ALL_CHANGED_FILES, it panic.
func Changes() (changeFiles []string, err error) {
	changes := os.Getenv("ALL_CHANGED_FILES")
	if changes == "" {
		err = newEnvError("ALL_CHANGED_FILES")
		return
	}
	changeFiles = strings.Fields(changes)
	return
}

// Repository returns owner and repository name for the current repository
//
// Example: goplus/llpkg, owner: goplus, repo: llpkg
// Repository extracts GitHub repository owner and name from GITHUB_REPOSITORY
func Repository() (owner, repo string, err error) {
	thisRepo := os.Getenv("GITHUB_REPOSITORY")
	if thisRepo == "" {
		err = newEnvError("GITHUB_REPOSITORY")
		return
	}
	current := strings.Split(thisRepo, "/")
	owner, repo = current[0], current[1]
	return
}

// Token returns Github Token for current runner
func Token() (token string, err error) {
	token = os.Getenv("GITHUB_TOKEN")
	if token == "" {
		err = newEnvError("GITHUB_TOKEN")
	}
	return
}

// LatestCommitSHA returns the current commit SHA from GITHUB_SHA environment variable
func LatestCommitSHA() (sha string, err error) {
	sha = os.Getenv("GITHUB_SHA")
	if sha == "" {
		err = newEnvError("GITHUB_SHA")
	}
	return
}

// WorkflowRunID returns the GitHub Workflow Run ID as an int64.
//
// It retrieves the GITHUB_RUN_ID environment variable. If the variable is not set,
// it panics. If the value cannot be parsed as an integer, it also panics.
func WorkflowRunID() (id int64, err error) {
	runId := os.Getenv("GITHUB_RUN_ID")
	if runId == "" {
		err = newEnvError("GITHUB_RUN_ID")
		return
	}
	id, err = strconv.ParseInt(runId, 10, 64)
	if err != nil {
		return
	}
	return
}
